#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "*:*:Picture in picture" state=floating

# turn on numlock
numlockx &

# for JAVA application
wmname LG3D

# show cursor when startup
xsetroot -cursor_name left_ptr

# polybar
/home/mizuyoru/.config/polybar/launch.sh &

# compositor
picom &

# lock screen after suspend
xss-lock -- /home/mizuyoru/Project/bash/lock.sh &

# random wallpaper per 30 mins
/home/mizuyoru/Project/bash/random_wallpaper.sh &

# Bluetooth Manager
blueman-applet &

#Clipboard manager
xfce4-clipman &

#Fcitx
XDG_CURRENT_DESKTOP=GNOME fcitx5 &

#Network-Manager
nm-applet --indicator &

#Notification
dunst &

#KDE-connect
#/usr/lib/kdeconnectd &
kdeconnect-indicator &

#earthquake alarm
"/opt/OXWU/Program/地牛Wake Up!" --hidden
