#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox:Toolkit sticky=on state=floating
bspc rule -a firefox:Devtools state=floating

# show cursor when startup
xsetroot -cursor_name left_ptr

# polybar
/home/mizuyoru/.config/polybar/launch.sh &

# compositor
picom &

# lock screen after suspend
xss-lock -- /home/mizuyoru/Project/bash/lock.sh &

# random wallpaper per 30 mins
/home/mizuyoru/Project/bash/random_wallpaper.sh &

# Bluetooth Manager
blueman-applet &

#Clipboard manager
xfce4-clipman &

#Fcitx
XDG_CURRENT_DESKTOP=GNOME fcitx5 &

#Network-Manager
nm-applet --indicator &

#Xfce Notification
/usr/lib/xfce4/notifyd/xfce4-notifyd &

#KDE-connect
/usr/lib/kdeconnectd &
